### ISSUE TITLE
Add a component that can display alerts in a fancy way 

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/clock-face#14]
A recent PR added a Halloween alert.  Let's move away from using the alert function and build a custom component to display an alert that will be passed in via props

**Comment by threadkind** [comment]
I'd like to work on this.

**Comment by threadkind** [comment]
Submitted a pull request for this.

**Comment by dfirebaugh** [comment]
Thank you for working on this! Nice job!

**Comment by dfirebaugh** [comment]
it happened!

**Comment by dfirebaugh** [comment]
https://dfirebaugh.github.io/clock-face/

**Comment by threadkind** [comment]
Awesome 😊🎃👻
Happy Halloween!
