### ISSUE TITLE
Add to the the theme

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/clock-face#5]
Add to the color palette

**Comment by nightrainlily** [comment]
What exactly are you thinking, just more colors? I think I could take this issue.

**Comment by dfirebaugh** [comment]
Yes, more colors!
Go for it, your choice!

The option to change between different color palettes would be cool, but not required.

**Comment by aniarya82** [comment]
Created PR[#11](https://github.com/dfirebaugh/clock-face/pull/11).
