### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/clock-face#6]

**Comment by gustafsilva** [comment]
I would like to help with this task :+1:, what kind of documentation are you thinking of?
I can initially create a `README.md` with information about Meetup and the project (dependencies and how to getting start). :rocket:

**Comment by dfirebaugh** [comment]
Hey, 
That sounds great.
As you might have read, this repo was used for an intro to React workshop.

Could you also link to the React Docs and this React cheat sheet.

I believe the start up of the project should just be a simple clone `npm install` `npm start`

thanks,
DF

**Comment by gustafsilva** [comment]
Great, i'll work on it! :+1:

**Comment by anonewb** [comment]
Hey!! try to close the issue once it's fixed and merged.
